language: ruby

# whitelist
branches:  
  only:
    - master

services:  
    #Enable docker service inside travis
    - docker

before_install:  
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:  
    #build the image
    - docker build --no-cache -t t2kllc/dotnet5 .
    #tag the build
    - docker tag t2kllc/dotnet5:latest t2kllc/dotnet5:v1
    #push the image to the repository
    - docker push t2kllc/dotnet5
